package pages;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import selenium.WebDriverWrapper;
import utils.Log4Test;

/**
 * Created by Illya
 */
public class MailPage extends BasePage {

    @FindBy(xpath = "//div[@id='gb']//a[contains(@href, 'SignOutOptions')]")
    private WebElement signOutOptionsLink;

    @FindBy(xpath = "//div[@class='gb_F']//a[contains(@href,'https://mail.google.com/mail/logout?')]")
    private WebElement signOutLink;  // this element has id='gb_71' - but seems to be autoGenerated

    @FindBy(xpath = "//div[@class='gb_fa']//a[contains(@href,'options')]")
    private WebElement otherAppsLink;

    @FindBy(xpath = "//div[@id='gbwa']//a[contains(@href, 'drive')]")
    private WebElement googleDriveLink;


    public MailPage(WebDriverWrapper driver) {
        super(driver);
    }

        //check if MailPage is active - button 'SignOut' is displayed
    public boolean isOnPage() {
        if (signOutOptionsLink.isDisplayed()) {
            Log4Test.info("User is logined");
            return true;
        } else {
            return false;
        }
    }

        //click on SignOutOption button
    public MailPage clickAccountOptionsLink() {
        signOutOptionsLink.click();
        return this;
    }

        //click on SignOut Button, return LoginPage
    public LoginPage clickSignOutLink() {
        Log4Test.info("Clicking on 'SignOut' button");
        signOutLink.click();
        return new LoginPage(driver);
    }

        //click on OtherApps Button
    public MailPage clickOtherAppsLink() {
        otherAppsLink.click();
        return this;
    }

        //choose GoogleDrive from OtherApps menu, return DrivePage
    public DrivePage clickGoogleDriveLink() {
        googleDriveLink.click();
        Log4Test.info("Switching to GDrive page");
        return new DrivePage(driver);
    }


}
